type User {
    id: ID
    name: String
    email: String
    password: String
    token: String
}

input UserInput {
    name: String
    email: String
    password: String
}

type Query {
    login(email: String, password: String): User
    users: [User]
} 

type Mutation {
    createUser(data: UserInput!): User!
}